"""Deterministic, stateless hashing + value noise.

Everything procedural in this project is derived from (seed, coordinates) so
that the same world can be regenerated byte-for-byte without storing every
single tile.  The LLM only fills in the *interesting* parts; this module
guarantees the boring parts are still coherent and reproducible.
"""
from __future__ import annotations

import hashlib
import math
from typing import Sequence, TypeVar

T = TypeVar("T")


def _digest(*parts) -> str:
    return hashlib.sha256("|".join(str(p) for p in parts).encode("utf-8")).hexdigest()


def hash_unit(*parts) -> float:
    """Uniform float in [0, 1) derived from arbitrary parts."""
    return int(_digest(*parts)[:13], 16) / float(16 ** 13)


def hash_int(*parts, mod: int) -> int:
    if mod <= 0:
        return 0
    return int(_digest(*parts)[:13], 16) % mod


def pick(seq: Sequence[T], *parts, default: T | None = None) -> T | None:
    if not seq:
        return default
    return seq[hash_int(*parts, mod=len(seq))]


def weighted_pick(pairs: Sequence[tuple[str, float]], *parts, default: str = "grass") -> str:
    total = sum(max(0.0, w) for _, w in pairs)
    if total <= 0:
        return default
    r = hash_unit(*parts) * total
    acc = 0.0
    for name, weight in pairs:
        acc += max(0.0, weight)
        if r <= acc:
            return name
    return pairs[-1][0]


def value_noise(seed, x: float, y: float, scale: float) -> float:
    """Smooth bilinear value noise in [0, 1)."""
    fx, fy = x / scale, y / scale
    x0, y0 = int(math.floor(fx)), int(math.floor(fy))
    tx, ty = fx - x0, fy - y0
    sx = tx * tx * (3 - 2 * tx)
    sy = ty * ty * (3 - 2 * ty)
    v00 = hash_unit(seed, x0, y0)
    v10 = hash_unit(seed, x0 + 1, y0)
    v01 = hash_unit(seed, x0, y0 + 1)
    v11 = hash_unit(seed, x0 + 1, y0 + 1)
    a = v00 + (v10 - v00) * sx
    b = v01 + (v11 - v01) * sx
    return a + (b - a) * sy


def fbm(seed, x: float, y: float, scale: float, octaves: int = 3) -> float:
    """Fractal noise in [0,1)."""
    total, amp, norm = 0.0, 1.0, 0.0
    s = scale
    for i in range(octaves):
        total += value_noise(seed + i * 977, x, y, s) * amp
        norm += amp
        amp *= 0.5
        s = max(1.0, s * 0.5)
    return total / norm if norm else 0.0


def jitter(seed, x, y, amount: float = 0.25) -> float:
    return (hash_unit(seed, "j", x, y) - 0.5) * 2.0 * amount
